### DISCUSSION TITLE
Guide docker-compose.yml for QNAP TS-2* (with Alpine 3.14)

### DISCUSSION THREAD

**Discussion by SiNaPsEr0x** [jheredianet/Teslamate-CustomGrafanaDashboards#37] [General]
I thought it was appropriate to help by creating the file for those like me who have a version of QNAP NAS with this specific kernel..
All you have to do is recreate the same file on your Container Station:
**With name container: teslamate**
```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    logging:      
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - ENCRYPTION_KEY=INSERT_YOUR_KEY
      - DATABASE_USER=teslamate
      - DATABASE_PASS=YOUR_PASS
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: arm32v7/postgres:14-alpine3.14
    restart: always
    logging:      
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=YOUR_PASS_DATABASE
      - POSTGRES_DB=teslamate
    ports:
      - 5432:5432
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    logging:      
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=YOUR_PASS_DATABASE
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana
      - /share/Container/container-station-data/application/teslamate/Teslamate-CustomGrafanaDashboards/customdashboards.yml:/etc/grafana/provisioning/dashboards/customdashboards.yml
      - /share/Container/container-station-data/application/teslamate/Teslamate-CustomGrafanaDashboards/dashboards:/TeslamateCustomDashboards

  mosquitto:
    image: seblucas/alpine-mosquitto:latest
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
#    command: -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
```
