### ISSUE TITLE
Use of TeslaMate datasource

### ISSUE THREAD

**Issue by rikardronnkvist** [jheredianet/Teslamate-CustomGrafanaDashboards#5]
Would be nice if you use the defined datasource named TeslaMate

Then it's possible to provision the dashboards direcly via a yaml-defintion like:

```
apiVersion: 1

providers:
- name: 'teslamate_custom'
  orgId: 1
  folder: TeslaMate Custom
  folderUid: xyzxyz
  type: file
  disableDeletion: false
  editable: true
  updateIntervalSeconds: 86400
  options:
    path: /teslamate/dashboards_custom

```

Then dropping the dashboard yaml's to the folder /teslamate/dashboards_custom

**Comment by jheredianet** [comment]
Great point @rikardronnkvist 
I'll try to make it that way. Thanks for your comment. I'll let you know when it's done.

**Comment by rikardronnkvist** [comment]
You should be able to auto-import these to Grafana if you do something like this in the compose-file of Teslamate...

```
services:
  grafana:
    volumes:
      - teslamate-grafana-data:/var/lib/grafana
      - /some/path/dashboards.yml:/etc/grafana/provisioning/dashboards/custom-teslamate.yml
      - /some/path/teslamate-custom:/teslamate-custom
```

And then you need to reference /teslamate-custom in the dashboard's yaml-file....
